### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by msradam** [keen/dashboards#101]
Would it be possible to have dashboards displayed in a dark theme?

**Comment by sayanmondal2098** [comment]
Can i go for it ?

**Comment by adamkasprowicz** [comment]
Hi @sayanmondal2098 !
yes please do, any involvement is highly appreciated 👍

**Comment by tiengiangproduction** [comment]
Suy nghi lai di..dug qua voi. Gap gap ma ket luan..ko nhu nhug gi tui noi
bao nhiu tui thền cho

Vào 3:34 Th 4, 10 thg 7 2019 Adam Kasprowicz <notifications@github.com> đã
viết:
