### ISSUE TITLE
Demos on github.io don't load

### ISSUE THREAD

**Issue by jlogsdon** [keen/dashboards#58]
[blocked] The page at 'https://keen.github.io/dashboards/examples/geo-explorer/' was loaded over HTTPS, but ran insecure content from 'http://d26b395fwzu5fz.cloudfront.net/3.1.0/keen.js?v=20141106': this content should also be loaded over HTTPS.

Github.io forces SSL these days.

**Comment by dustinlarimer** [comment]
Fixed - thanks @jlogsdon
