### ISSUE TITLE
Refresh charts on resize

### ISSUE THREAD

**Issue by seanr** [keen/dashboards#61]
If you resize your browser window, you get some pretty crazy weirdness with the charts overflowing containers and have to reload the page to get them to look right.  It'd be nicer to detect the resize if possible and just refresh the chart objects automatically.

**Comment by dustinlarimer** [comment]
@seanr most of the demos use the Google Charts rendering adapter of our SDK. Unfortunately, that library does not support fluid, responsive charts the way one would hope. Once the screen loads, charts will maintain that width. It's something we would like to work around, perhaps in a future release of keen-js.
