### ISSUE TITLE
Add viewport meta for correct viewing on tablets and other devices

### ISSUE THREAD

**Issue by tacohiddink** [keen/dashboards#67]
Please add this to support correct scaling on tablet devices:

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />`

**Comment by dustinlarimer** [comment]
@tacohiddink sure thing, which demo/pages should include this?

**Comment by tacohiddink** [comment]
I guess on all of the layouts and example pages

**Comment by dustinlarimer** [comment]
@tacohiddink done - thanks!
