### ISSUE TITLE
Make backends/APIs pluggable

### ISSUE THREAD

**Issue by otisg** [keen/dashboards#68]
I'm considering using Keen IO Dashboards in my own project, but would like to be able to plug in a different backend, with a different API.  I'm guessing this is currently not possible.  Is this something that could be abstracted to make it possible for others to call different backends with different APIs/queries, but still use Keen IO Dashboards?

**Comment by plasmaphonic** [comment]
+1 Otisg -- I need to do the same.

**Comment by mallim** [comment]
+1

**Comment by dzello** [comment]
Thanks for opening the issue!

In fact, you can use dashboards to display data from any source. Basically you'd grab the data in JavaScript then pipe it to a charting library or to [keen-js](https://github.com/keen/keen-js) (which can take arbitrary data for charting purposes) for plotting.

**Comment by jchris** [comment]
Anyone have an example project where they did this? I bet a lot of people would click a link to one.

**Comment by adamkasprowicz** [comment]
https://github.com/keen/keen-dataviz.js
or use any other charting lib like https://chartjs.org , highcharts or other
