### ISSUE TITLE
Bower package is empty

### ISSUE THREAD

**Issue by aendrew** [keen/dashboards#79]
I don't know why, but `bower install keen-dashboards` results in a license, a README, and nothing else.

Which is a shame, really; you could easily install the necessary CSS and whathaveyou by specifying it as such in the `main` stanza, which would mean folks like me who use `Yeoman` could use your layouts far more easily.

Might write a PR.

**Comment by josephwegner** [comment]
Thanks for writing this up @aendrew. Admittedly, we haven't spent much time on more involved ways of distributing Keen Dashboards (bower, yeoman, etc.). That would be super cool if you wrote up a PR!

**Comment by timfalls** [comment]
@aendrew just wanted to echo @josephwegner's encouragement toward the PR. We really appreciate your thoughts and any potential contribution!

**Comment by standaniels** [comment]
I don't know anything about bower, but I just came across [this SO topic](http://stackoverflow.com/questions/29046960/bower-json-main-is-present-but-i-get-a-is-missing-main-entry-in-bower) and noticed that there is only a bower.json file in the master branch of this project.

**Comment by aendrew** [comment]
@standaniels Ah! That would make sense why there's nothing when pulling from bower. If the gh-pages branch was merged with master, that would probably resolve this.

**Comment by dustinlarimer** [comment]
Resolved- thanks, everyone!
