### ISSUE TITLE
Where is the meta.js asset file?

### ISSUE THREAD

**Issue by naisanza** [keen/dashboards#84]
For example the hero sidebar layout specifies a meta.js file here:

https://github.com/keen/dashboards/blob/gh-pages/layouts/hero-sidebar/index.html#L171

But no where does it explain where to acquire it

I'm guessing it's this one:

https://github.com/abbotto/meta-js/tree/master/build

But the layout doesn't look right.

[screenshot](http://i.imgur.com/GIABsbg.png)

**Comment by naisanza** [comment]
Fixed the layout by using bootstrap.min.css from bootstrap-3.3.6

**Comment by dustinlarimer** [comment]
@naisanza fixed in the latest update- thanks for finding that 👍
