### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by amartone** [keen/dashboards#87]
Hello,

Great dashboards! 

Are there plans to build for Bootstrap 4 in the future?

**Comment by tbarn** [comment]
@amartone Good question! I'll see if I can dig up an answer.

**Comment by tbarn** [comment]
Hey @amartone! I don't have a good answer on this yet. 😕 Maybe after Boostrap 4 is out of alpha. If anything changes, we will let you know!

**Comment by Lucid-Network** [comment]
I would lso be interested in a b4 version. Any news now that the beta is out maybe?

**Comment by arnzel** [comment]
any update on this ?

**Comment by dustinlarimer** [comment]
@arnzel no plans to pursue this in the near-term, but it would make for a great #hacktoberfest contribution if someone wants to pick it up 👍

**Comment by apryka** [comment]
dashboards have been updated with CSS grid, so bootstrap dependencies are removed in [v.3.0.0](https://github.com/keen/dashboards/releases/tag/v3.0.0)
