### ISSUE TITLE
Is this repo being actively maintained?

### ISSUE THREAD

**Issue by ammaskartik** [keen/dashboards#91]
This looks great, and we would love to use it; but I been asked if this repo is still being actively maintained or not, as there is a gap since last code commit.

**Comment by dustinlarimer** [comment]
Hey, @ammaskartik – thanks for the note! Is there anything in particular that we could do to improve this project?

**Comment by dustinlarimer** [comment]
Closing for now- always eager to discuss any ideas or questions you may have 👍
