### ISSUE TITLE
Usage instructions don't match repo

### ISSUE THREAD

**Issue by okko** [keen/dashboards#97]
https://github.com/keen/dashboards#usage instructs to navigate to your keen project or to go to the repository and navigating to demo-data, to see javascript files. There's no folder "demo-data" in the repo. It appears that in the keen project one needs to navigate to Explorer, create a new query, save it and then choose "Embed" button to get the javascript code mentioned.

**Comment by dustinlarimer** [comment]
@okko thanks for the note- I've restored the file in question. We appreciate your help! https://github.com/keen/dashboards/blob/gh-pages/demo-data/sample.html
