### ISSUE TITLE
Usage instructions don't match repo (cont.)

### ISSUE THREAD

**Issue by htarnoff** [keen/dashboards#98]
This issue is a continuation of the issue entitled "Usage instructions don't match repo" #97 that was closed (and I cannot reopen).

Please see the discussion of Issue #97 for background information.

The restored _demo-data/sample.html_ file seems to be incorrect. It uses a client.draw() function calls where no draw() function seems to exist. As a result, the usage instructions will still not enable anyone to get an example of the repo up and running, at least not quickly. 

I investigated, and I figured out that, if one replaces the cutting and pasting of the erroneous content of the sample.html file with a script reference to the file _examples/starter-kit/starter-kit.js_, the quick start process can be made to work. Reason: That script uses client.query() instead of client.draw(), and client.query() is a function that actually exists (and seems to work).

Script reference placed just before the </body> tag:

`  <script type="text/javascript" src="/examples/starter-kit/starter-kit.js"></script>`

I would also like to suggest that whoever attempts to correct this issue should verify that the solution works from the POV of the current repo, lest this issue linger one. It seems to be a major barrier for repo adoption by new users.

**Comment by antislice** [comment]
Also, the instructions for using an existing Keen query are essentially nonexistent. The instructions for step 4 and on only reference sample.html. Because I remembered the "Embed" button from Keen's UI and can parse the code well enough, I got the chart to show up in my new dashboard.

**Comment by antislice** [comment]
Noticed another thing - the sample layouts don't seem to play nice with the embed snippets from inside keen. Since I imagine many people will be trying to do that it would be nice if it all worked together.

**Comment by apryka** [comment]
_demo-data/sample.html_ has been updated with the latest version of sdks here [v.3.0.1](https://github.com/keen/dashboards/releases/tag/v3.0.1)
